sudo: required
language: generic

services:
  - docker

before_install:
  - docker --version
  - docker pull fedtech/enterprise:latest || true

install:
  - docker build --pull --cache-from fedtech/enterprise:latest --target builder -t fedtech/enterprise:test .

script:
  - mkdir coverage
  - docker run -v "$PWD/coverage:/usr/src/app/coverage" fedtech/enterprise:test yarn run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t fedtech/enterprise:latest .

deploy:
  skip_cleanup: true
  provider: script
  script: docker push fedtech/enterprise:latest
  on:
    branch: master
