sudo: required
language: generic

services:
  - docker

before_install:
  - docker --version

install:
  - docker build --target builder -t fedtech/enterprise:test .

script:
  - mkdir coverage
  - docker run -v "$PWD/coverage:/usr/src/app/coverage" fedtech/enterprise:test yarn run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t fedtech/enterprise:latest .
  - docker push fedtech/enterprise:latest
