sudo: required

language: generic

services:
  - docker

before_install:
  - docker --version

install:
  - docker build --target builder -t blaenk/enterprise-api .

script:
  - docker run blaenk/enterprise-api yarn test --colors
