sudo: required

language: generic

services:
  - docker

before_install:
  - docker --version

install:
  - docker build --target builder -t blaenk/enterprise-api .

script:
  # Pass CI's environment variables into docker.
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env blaenk/enterprise-api yarn run coverage
