sudo: required

services:
  - docker

before_install:
  - docker --version

install:
  - docker build --target builder -t blaenk/enterprise-api .

script:
  - docker run -t blaenk/enterprise-api yarn test
