sudo: required
language: generic

env:
  global:
    secure: oT7rOt20DSdZYvtCp+3lPnx5xnNtD766pO102FX/uPhPoHVC4eYOfr6dG0bKsq6kr9TWxAaRXBrk1ZF/Urc0PP8v4sXrqhz6vATOZkg99E+HsoogwGlgDR9KmSbfVvNSDsnfFu3iUseQF4J+5y/enDR/1HN/ipkUrxdXACdl1Vnq5Oc5u3mAonw0FSVmt/CDhUAf8GKp5cdJEf6ELlbiGERxQBssjB4SdXUGwo47lBFyMKeeKUEPYN5czr5fRmZti4GdInRJki2MFAd2pAHP7ebf8aSt54rY1pLWeTB3valMtIVgqdItI5yxotQXwqXFWt/SkPtvTT1ecPkT4gVcVaHyIV5cziR4eZanf4zM5HD4g5OPOo+8xhsQA7a6SWBRISmAxwda4D2b90lknlUpAcK5YmB2XM3PkxMIbAcb9QlbEH+r5q9oymWoXwa4AgUEoovpq+BhKiexmRghA1kIz88SCWoX4AKPSrGKyL3bqbSfjVdSdSW8/n5bPwt17OXq4e4CmjQVHrLmldbqwzw+W2GOUCRMdiWmqPPzkv2jzfSuFEy79rPDih7YBGAzDr2dWISTrdNd3Rv5x50ygxmj+MRnlT/SU7pGm8og/q174fqcbGWrR+M+h1iexUi6ty6wCAWjwOcHtv6EQPoSyjDfA2WcbpQNQm9+wsOVdJctMSw=

services:
  - docker

before_install:
  - docker --version

install:
  - docker build --target builder -t blaenk/enterprise-api .

script:
  - mkdir coverage
  - docker run -v "$PWD/coverage:/usr/src/app/coverage" blaenk/enterprise-api yarn run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage
