version: '3.6'
services:
  api:
    build:
      context: .
      target: builder
    image: fedtech/enterprise:dev
    command: ["yarn", "run", "start:live"]
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

  nginx:
    build:
      context: ./nginx
    image: fedtech/nginx:enterprise
    ports:
      - '8000:80'
    volumes:
      - "${ENTERPRISE_WEB_PATH}/static/:/usr/share/nginx/html"

  postgres:
    build:
      context: ./postgres
    image: fedtech/postgres:enterprise
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  db-data:
