version: '3.6'
services:
  api:
    build:
      context: .
      target: builder
    image: fedtech/enterprise:dev
    command: ["yarn", "run", "start:live"]
    environment:
      - IS_SERVICE=1
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

  nginx:
    build:
      context: ./docker/nginx
    image: fedtech/nginx:enterprise
    ports:
      - '8000:80'
    volumes:
      - "${ENTERPRISE_WEB_PATH}/static/:/usr/share/nginx/html"
    depends_on:
      - api

  postgres:
    build:
      # NOTE: The context is set to ./db/ and the Dockerfile path is expressed
      # relative to that context. This is done so that the SQL files can live
      # outside of the docker-specific directories.
      context: ./db/
      dockerfile: ../docker/postgres/Dockerfile
    image: fedtech/postgres:enterprise
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    build:
      context: ./docker/redis
    image: fedtech/redis:enterprise
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  db-data:
