apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: blaenk/enterprise-api
deploy:
  helm:
    releases:
    - name: enterprise-api
      chartPath: chart
      namespace: default
      #valuesFilePath: helm-skaffold-values.yaml
      values:
        imageName: blaenk/enterprise-api
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue
