apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: blaenk/enterprise
deploy:
  helm:
    releases:
    - name: enterprise
      chartPath: chart
      namespace: default
      #valuesFilePath: helm-skaffold-values.yaml
      values:
        imageName: blaenk/enterprise
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue
